# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TdFile < Formula
  desc "A terminal based todo TUI backed by your own todo file. Clean collapsible tree UI, real-time file sync, and robust markdown file support."
  homepage "https://github.com/camin-mccluskey/td-file"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/camin-mccluskey/td-file/releases/download/v1.0.0/td-file_Darwin_x86_64.tar.gz"
      sha256 "e2f568e0b09b615219c84ee84238e866a8792c221048f09888f8f04ebae241ad"

      def install
        bin.install "td-file"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/camin-mccluskey/td-file/releases/download/v1.0.0/td-file_Darwin_arm64.tar.gz"
      sha256 "c0f9de9a8e11bde9879367e7466e63a662404234982f5197a6ff2099e8ea2489"

      def install
        bin.install "td-file"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/camin-mccluskey/td-file/releases/download/v1.0.0/td-file_Linux_x86_64.tar.gz"
      sha256 "cca5e94a2fdc2e9c805977c3bb391707ef1a10af2dd4f4f4dc9af53336723cce"
      def install
        bin.install "td-file"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/camin-mccluskey/td-file/releases/download/v1.0.0/td-file_Linux_arm64.tar.gz"
      sha256 "4cd071d36b822274067d077e5b0c4ef70078f790159771941fd561015fa44bb3"
      def install
        bin.install "td-file"
      end
    end
  end
end
